/* eslint-disable max-len */
export const dataContents: any = [
  {
    id: 2,
    content_name: "Baru Rilis",
    type: 1,
    active: 1,
    created_at: "2022-09-19T18:49:46.000000Z",
    updated_at: "2022-09-19T18:49:46.000000Z",
    novels: [
      {
        id: 14,
        novel_price: 29,
        novel_uri: "bukan-salah-ibu-mengandung-tqH",
        novel_title: "Bukan Salah Ibu Mengandung",
        novel_sinopsis:
          "Cerita ini terinspirasi dari kisah nyata yang di mana Juwita Maharani (nama samaran),\nadalah seorang wanita yang terlahir di tengah-tengah keluarga non muslim jatuh cinta pada\npria yang berbeda kepercayaan dengannya. Namun, bukan cinta saja yang membuatnya\nmemilih jalan lain, meninggalkan orang tua, dan sanak saudara. Juwita berpindah kepercayaan\nkarena dia juga berpikir bahwa agama yang dianutnya saat ini adalah jalan kebenaran.\nSetelah mengucapkan dua kalimat syahadat, rentang waktu tiga bulan lamanya, Juwita\npun dilamar oleh pria yang dicintai, yaitu Fatih Herlambang di usianya 26 th, sedangkan Juwita\nberusia 23 th kala itu.\nHubungan yang manis dan keluarga harmonis, hanya dirasakan Juwita beberapa bulan\nsaja. Selain perhatian Fatih yang mulai berkurang, keluarga besar Fatih juga memperlakukan\nJuwita semena-mena, tak ubah seperti seorang pembantu di rumah itu. Namun, Juwita tetap\nsabar menghadapi segala apa yang telah menimpanya. Dia menganggap semua itu adalah ujian\ndari Sang Pencipta karena telah memeluk agama yang diridhoi Allah Subhanahu wa ta&#39;ala.\nOrang ketiga pun hadir di antara Juwita dan Fatih. Rosita namanya, dia adalah mantan\nkekasih Fatih yang berprofesi sebagai model endors-an beberapa produk kosmetik dan\npakaian. Rosita pun sudah menjanda setelah usia pernikahannya baru berjalan beberapa bulan\nsaja. Tentu itu mempermudah Rosita untuk mendekati Fatih—pria yang masih bertahta di\nlubuk hatinya yang terdalam.\n\nPertengkaran tak bisa dielakkan, nasi pun sudah menjadi bubur. Juwita terpaksa\nmengambil jalan perpisahan karena Fatih tanpa merasa iba, dia telah menyakiti Juwita terang-\nterangan.\nPasca perceraian, Juwita pun memutuskan untuk pulang ke kampung walau kedua\norang tuanya sudah tiada. Dia berharap kakaknya bisa menerima kehadiran dia dan juga\nFarel—si buah hati.\n\nBersyukur, ternyata kakak Juwita menerima dengan baik. Bahkan, setelah Juwita\nmenceritakan semua apa yang telah diperbuat oleh Fatih dan keluarganya, kakak Juwita\nberang, ingin membalas perbuatan mereka. Akan tetapi, Juwita meminta kakaknya untuk\nbersabar.\nKarena kakak Juwita juga orang susah dan suaminya juga di PHK sebab sakit-sakitan,\nmereka memutuskan untuk menjual rumah peninggalan orang tua. Hasilnya mereka gunakan\nuntuk membayar uang pengobatan, membayar utang-utang kedua orang tua mereka, dan\nsisanya dibagi untuk modal usaha kecil-kecilan.\nSetelah Juwita mendapat bagiannya, dia pun memutuskan untuk mencari kerja di kota\nJakarta. Yang namanya mempunyai anak kecil, tentu saja akan susah mencari pekerjaan yang\npas. Akhirnya Juwita memutuskan untuk ikut bersama Wati sepupunya, yaitu bekerja sebagai\npemulung.\nSuka tidak suka, kehidupan baru pun dimulai. Bertarung dengan pemulung lain, saling\nberebut barang rongsokan, dan berkelahi dengan waktu, juga cuaca yang kadang tak menentu.\nTidak itu saja, Juwita juga tinggal di gubuk berdinding separuh kardus, beratap seng bekas yang\nsebagiannya sudah tiris, tetapi dia tetap menganggap itu adalah sebuah rumah yang bisa\nmelindunginya dari terik mentari, dan hujan.\nAkan tetapi, ada sesuatu yang membuat Juwita bisa lebih bernapas dengan lega karena\nada seorang wanita baik hati di pemukiman para pemulung mau mengasuh Farel, sebab\nanaknya juga sebaya dengan anak Juwita. Membuat Juwita tidak perlu cemas lagi harus\nmembawa putranya itu ke sana kemari.\nBerjalan beberapa bulan saja, Juwita pun kembali berpikir untuk mencari pekerjaan\nyang lebih layak. Dia ingin mendapatkan gaji yang bisa membelikan putranya makan-makanan\nsehat, tanpa harus memungut makanan kotor dari tong sampah lagi. Juwita melamar ke\nsebuah pabrik sepatu di Tangerang. Dia pun diterima karena ijazah terakhirnya juga cukup\nmembantu. Namun, agar dia bisa lebih fokus bekerja, Juwita pun menitipkan Farel pada Bu\nJulaeha—mertuanya. Walau dia selalu mendapatkan perlakuan buruk dari sang mertua,\nmungkin Farel sebagai cucu di keluarga itu, tidak akan disakiti sebagaimana dia disakiti oleh\nkeluarga mantan mertuanya.\nJuwita akhirnya bekerja di pabrik itu, tinggal di indekos milik Bu Rita. Dia juga bertemu\ndengan orang-orang baik dan juga mempunyai sahabat terbaik yang lebih muda darinya. Di\npabrik tersebut, Juwita juga mendapatkan perlakuan spesial dari pria yang bernama Wisnu.\nNamun, tetap saja ada orang-orang yang ingin menyakiti, dan menjatuhkan dia.\n\nBerselang beberapa bulan bekerja di tempat itu, Wisnu pun menyatakan perasaannya\nterhadap Juwita. Awalnya Juwita ragu karena dia cukup trauma dengan perlakuan mantan\nsuaminya, Fatih. Akan tetapi, Wisnu berhasil meyakinkan Juwita. Juwita pun akhirnya\nmenerima cinta Wisnu.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665415420_gooddreamer_0.jpg",
        novel_rating: 4.5,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-10 23:23:16",
        created_at: "2022-10-10T15:23:40.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-12-21 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 35008,
        purchased: true,
        listed: true,
        total_purchased: 9,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 9,
            category_name: "Action",
            created_at: "2022-10-16T12:52:55.000000Z",
            updated_at: "2022-10-16T12:52:55.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 15,
        novel_price: 29,
        novel_uri: "cinderella-tanpa-nama-tJY",
        novel_title: "Cinderella Tanpa Nama",
        novel_sinopsis:
          "Naknak adalah seorang gadis kecil yang dibuang dan tidak diinginkan, hingga akhirnya dia\nberjumpa dengan seorang ibu adopsi dan memberinya nama. Penyesalan ibu kandungnya\nmembuat dia harus menemukan Naknak kembali. Dia akhirnya berjumpa dengan Sonia dan\nKiki. Tetapi ibu kandungnya bingung memilih di antara Sonia dan Kiki yang mana\nsebenarnya Naknak.\n\nNaknak merasa nasibnya seperti Cinderella, hanya saja Cinderella sengsara karena ibu\ntirinya. Sementara Naknak menderita karena ibu kandungnya.\n\nSebenarnya Naknak adalah gadis yang kuat, tetapi di dalam perjuangan hidupnya Naknak\nmasih belum bisa menerima kehadiran ibunya, Audy. Ketika dia akhirnya dapat menerima\nibunya, hatinya kembali terhempas setelah mengetahui alasan dia terlahir ke dunia ini. Hati\nNaknak kembali terluka, hingga akhirnya seorang pangeran datang menolong dan menarik\ndia keluar dari jurang yang dalam.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665420707_gooddreamer_WhatsApp-Image-2022-10-07-at-20.35.19.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-11 01:26:06",
        created_at: "2022-10-10T16:51:47.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-20 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 9,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 9,
            category_name: "Action",
            created_at: "2022-10-16T12:52:55.000000Z",
            updated_at: "2022-10-16T12:52:55.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 17,
        novel_price: 29,
        novel_uri: "lets-talk-about-everything-again-INw",
        novel_title: "Let’s Talk About Everything Again",
        novel_sinopsis:
          "Shanien Adyatma dan Reksa Soedjatkimo adalah pasangan suami istri yang bercerai tiga\ntahun lalu. Ketidaksiapan mereka dalam menghadapi kehidupan pernikahan dan hadirnya\norang dari masa lalu Reksa membuat pernikahan itu mencapai batas usai. Namun, tidak\ndapat dipungkiri bahwa rindu dan cinta masih membekas di antara keduanya, walaupun\ntidak pernah sempat terucapkan bahkan sampai di hari mereka bercerai.\nTiga tahun lamanya Shanien mengurus putri semata wayangnya hingga tiba-tiba, Reksa hadir\nkembali menawarkan rasa baru di hati Shanien. Dengan pikiran yang lebih dewasa, mental\nyang lebih siap, juga sikap yang tegas, akankah mereka bisa kemblai lagi menata hati yang\npernah reta? Atau memang mereka sudah usai?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665630943_gooddreamer_IMG_20221007_172510.jpg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 13:10:21",
        created_at: "2022-10-13T03:15:43.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-16 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 20,
        novel_price: 29,
        novel_uri: "salam-untuk-sang-malam-end-of-the-hail-zE3",
        novel_title: "SALAM untuk SANG MALAM – End of the Hail",
        novel_sinopsis:
          "“Di dunia di mana ilmu pengetahuan adalah segalanya. Semua kegilaan menjadi biasa saja.”\nNolan hanyalah seorang anak bodoh yang keberadaannya tak diharapkan. Hingga pada suatu malam\nia dibawa ke sebuah istana yang akan jadi awal dari masa depannya yang penuh dengan gejolak.\nMulai dari pertemuan dengan seorang pewaris tak diharapkan. Sampai bagaimana ia berhasil\nmenguak rahasia besar kecacatan sekelompok orang yang selama ini dianggap tuhan. Bagaimana ia\ntumbuh jadi anak remaja dengan masa lalu penuh beban. Sampai perjumpaan dengan anak remaja\nyang ingin jerumuskan dunia dalam kehancuran.\n\nSemua kejadian, baik hal buruk maupun sebaliknya, terus terajut menjadi bagian dari benang takdir\nyang menyusun kenyataan.\nSampai waktu di mana berdengungnya salam terakhir.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665637760_gooddreamer_WhatsApp-Image-2022-10-10-at-11.28.39.jpeg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 13:21:45",
        created_at: "2022-10-13T05:09:22.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 4,
            category_name: "Sains Fiksi",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 8,
            category_name: "Thriller",
            created_at: "2022-10-16T12:52:34.000000Z",
            updated_at: "2022-10-16T12:52:34.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 64,
        novel_price: 29,
        novel_uri: "kesatria-bumi-CCK",
        novel_title: "Kesatria Bumi",
        novel_sinopsis:
          'Lily menemukan bahwa sebagai keturunan setengah nimfa, leluhurnya, Mantica, adalah sumber dari perpecahan yang memicu kebrutalan Olimpus.\nMantica adalah nimfa paling rupawan yang bejat, menyesatkan para dewa dewi hingga mereka bertekuk lutut memujanya. \nZeus terjerat oleh pesona Mantica dan sanggup berkhianat dari Hera.\nKini Lily mengetahui alasan yang tepat, kenapa ratu Olimpus begitu membenci dirinya.\nTanpa disangka oleh siapa pun, Mantica yang terkubur di laut hitam bangkit dan menginginkan kembali kejayaannya dengan menjadi permaisuri Zeus dan menguasai dunia. \nMantica telah membelah jiwanya menjadi tiga. Satu jiwa di alam transisi, kedua dalam diri Arethusa dan ketiga dalam tubuh Lily. \nApakah kali ini Lily harus menumpas leluhurnya, demi menciptakan kedamaian di muka bumi?\n"Takdirmu adalah meruntuhkan Olimpus. Bela bumi ini dari mereka yang tidak menginginkan kita menginjak tanah yang sama dalam damai!”\nKisah ini tentang perjuangan, cinta yang tersakiti, juga persahabatan yang tiada akhir. Pahlawan adalah makhluk seperti kita, memiliki sisi lemah dan rapuh. \nHanya saja, mereka selalu punya cara untuk bangkit, menyingkirkan segala kepentingan pribadi demi menyelamatkan yang lain!\nInilah perjalanan para pembela bumi yang berjuang hingga titik darah terakhir, tanpa diketahui oleh manusia yang saat ini berusaha merusak dengan cara mereka sendiri!',
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665729376_gooddreamer_WhatsApp-Image-2022-10-11-at-22.09.55.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 14:03:31",
        created_at: "2022-10-14T06:36:17.000000Z",
        updated_at: "2022-12-07T03:14:14.000000Z",
        expired_at: "2023-01-07 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: true,
        listed: true,
        total_purchased: 6,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 4,
            category_name: "Sains Fiksi",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 65,
        novel_price: 29,
        novel_uri: "pesan-pasien-tak-kasat-mata-4aP",
        novel_title: "Pesan Pasien Tak Kasat Mata",
        novel_sinopsis:
          "Setiap insan manusia yang dilahirkan pasti memiliki kekurangan. Tak terkecuali aku—Bian Alvaro.\nDilahirkan dengan kondisi ANOSMIA (Kehilangan indera penciuman secara total atau sebagian)\nTak kusangka, kekurangan yang membuatku sangat berbeda dari orang kebanyakan, ternyata,\nmenjadikan suatu kelebihan yang bisa mengantarkan aku menjadi dokter forensik.\nHal yang mengejutkan lainnya, satu persatu pengalaman melihat yang tak kasat mata di ruang\nautopsi ketika menjalani tugas.\nPengalaman horror yang membuatku merinding semakin intens. Awalnya, aku bingung, tak\npercaya pada hal ghaib. Lambat laun, rasa takut dan tak percaya mulai menghilang.\nPesan-pesan dari pasien tak kasat mata semakin banyak dan membuatku kelabakan selama\nmenjadi dokter forensik. Kejadian-kejadian aneh semakin banyak di sekitarku. Apakah aku\nsanggup menjalani profesi sebagai dokter forensik ini? Misteri masa lalu pun terkuak ke\npermukaan, apa yang harus aku lakukan untuk menghadapi itu semua?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665729616_gooddreamer_Black_Queen---PPTKM.jpeg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 14:23:01",
        created_at: "2022-10-14T06:40:16.000000Z",
        updated_at: "2022-11-19T11:52:10.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 1,
        categories: [
          {
            id: 7,
            category_name: "Horor",
            created_at: "2022-10-14T03:32:22.000000Z",
            updated_at: "2022-10-14T03:32:22.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 66,
        novel_price: 29,
        novel_uri: "janji-mecca-KHy",
        novel_title: "Janji Mecca",
        novel_sinopsis:
          "Tentang sebuah janji seorang perempuan bernama Mecca pada sahabatnya dan pada seseorang di masa lalunya. Mecca, berjanji pada Faris akan menunggunya hingga ia berhasil mencapai kesuksesan dan menjawab ucapan cintanya. Mecca pun berjanji pada Khaira akan membuatnya bahagia, apapun yang Khaira mau akan diberikannya.\n\n \n\nLalu bagaimana jika ternyata Khaira menginginkan Faris? Dalam diam Mecca merasa terhimpit di dalam dua janji yang dia buat sendiri. Apakah yang membuat Mecca akhirnya lebih mementingkan janjinya pada Khaira? Lalu bagaimana keadaan Faris?\n\n \n\nSimak cerita selengkapnya di Janji Mecca, bukan hanya persoalan cinta segitiga, persahabatan tapi tentang keluarga dan juga kehidupan lainnya.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665730776_gooddreamer_Nisa-Noor--JM.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 14:28:23",
        created_at: "2022-10-14T06:59:36.000000Z",
        updated_at: "2022-11-19T11:52:10.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 3,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 67,
        novel_price: 29,
        novel_uri: "love-scenario-dSC",
        novel_title: "Love Scenario",
        novel_sinopsis:
          "Kisah kehidupan antara sepasang kekasih yang terjalin dari bangku SMA,  di mana Ayra gadis cantik dan periang harus melanjutkan kuliahnya di Jakarta sedangkan Alfero kekasihnya kuliah di Singapore sesuai permintaan kedua orang tuanya. Mereka harus terpisah jarak, dan menjalani sebuah hubungan yang disebut dengan Long Distance Relationship (LDR).\n\nSetelah Alfero menyelesaikan pendidikan sarjananya, Alfero pun kembali ke Indonesia dan mereka\nkembali bersama, hanya saja disaat Perusahaan Papa Alfero mendapatkan masalah besar,  Alfero pun pergi ke Italy meninggalkan Ayra kembali pergi tanpa pamit dengan Ayra, dan membuat hubungan mereka pun semakin merenggang. \n\nBagaimanakah skenario cinta mereka berjalan? Apakah Ayra masih sanggup menunggu sang kekasih, yang meninggalkannya tanpa pesan?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665731146_gooddreamer_Uthieecan---LS.jpeg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 14:23:30",
        created_at: "2022-10-14T07:05:46.000000Z",
        updated_at: "2022-11-19T11:52:10.000000Z",
        expired_at: "2022-12-03 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: true,
        listed: true,
        total_purchased: 3,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 68,
        novel_price: 29,
        novel_uri: "the-everlasting-lullaby-FyS",
        novel_title: "The Everlasting Lullaby",
        novel_sinopsis:
          "Niat hati ingin mengakhiri rantai ironi dalam hidupnya, Iva justru kembali dihadapkan pada takdir yang semakin rumit setelah tiba-tiba terbangun dalam tubuh Titania. Meski begitu ia tidak menyerah begitu saja, Iva masih mencoba meninggalkan dunia-membunuh dirinya sendiri, sampai suatu hari sosok yang diagungkan para elf muncul.\n\nDewa Freyr menampakkan diri di hadapan Iva untuk menjelaskan alasan gadis itu terbangun di tubuh Titania. Siapa sangka sebuah Iva mengemban tugas yang berat dan mempertaruhkan keselamatan dua dunia, sehingga sang dewa menawarkan perjanjian kepada Iva. \n\nLantas, Apakah ia akan tetap berusaha mengakhiri hidupnya atau menerima tawaran untuk menjalankan tugas dari sang dewa? Perjanjian apa yang ditawarkan Freyr kepada Iva?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665732457_gooddreamer_Audreana-Ivy---TEL.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 14:54:25",
        created_at: "2022-10-14T07:27:38.000000Z",
        updated_at: "2022-11-19T11:52:10.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 3,
        categories: [
          {
            id: 2,
            category_name: "Fantasi",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 76,
        novel_price: 29,
        novel_uri: "dendam-si-bahan-taruhan-1c1",
        novel_title: "DENDAM SI BAHAN TARUHAN",
        novel_sinopsis:
          "Davin mahasiswa kedokteran, dijadikan bahan taruhan oleh sahabatnya sendiri yang bernama Alan. Karena taruhan itu, Davin dituduh sebagai pengedar obat terlarang. Beasiswanya dicabut, dikeluarkan dari sekolah, bahkan dijauhi oleh teman-temannya. Dan yang paling parah adalah, ayahnya yang sudah sakit-sakitan mengalami serangan jantung mendadak kala mendengar semua berita itu. Davin shock bukan main, dia kehilangan semua dan sebatang kara dalam waktu sekejab. Dendam yang membara berlabuh di dalam hatinya. \n\tDavin bertemu orang baik, hingga dirinya disekolahkan kembali di luar negeri. Saat kembali, ia menjadi dokter spesialis jantung yang sangat hebat. Dia mulai melakukan rencana balas dendamnya, seperti merebut pekerjaan Alan, mencuri semua perhatian yang selama ini ditujukan untuk Alan sebagai dokter terbaik. Hingga bahkan, Davin menggoda calon istri Alan agar meninggalkan lelaki itu. Tentu saja Davin semakin membabi buta balas dendam.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665968555_gooddreamer_Cover_Dendam-Si-Bahan-Taruhan.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-17 08:48:31",
        created_at: "2022-10-17T01:02:35.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    content_name: "Top 10",
    type: 3,
    active: 1,
    created_at: "2022-09-19T18:51:00.000000Z",
    updated_at: "2022-10-13T11:36:30.000000Z",
    novels: [
      {
        id: 43,
        novel_price: 29,
        novel_uri: "ku-temukan-cinta-dalam-sujudku-bGW",
        novel_title: "Ku Temukan Cinta Dalam Sujudku.",
        novel_sinopsis:
          "Bola mata jernih dan indah milik gadis manis bernama Aqila itu terlihat berkaca-kaca saat menyaksikan adik kesayangannya bersanding dengan lelaki yang lebih dulu melamarnya..\nSeminggu yang lalu, Aqila di lamar oleh kekasih yang dicintai nya yaitu, Haris. Entah apa yang terjadi sehingga yang duduk di pelaminan itu bukan dirinya melainkan sang adik tercinta.\nTiga tahun berlalu, Haris kembali melamar Aqila  disaat dia sudah di lamar   oleh pengusaha muda yang tampan dan bijak sana bernama Nazriel Al-Fatih.\nAqila dilanda dilema yang hebat saat ia harus mempertimbangkan permintaan sang adik tercinta untuk menikah dengan Haris dan merawat anaknya sedangkan pada saat ini, hatinya sudah terpaut pada sosok Nazriel.\nAkankah Aqila menuruti permintaan adik tercinta nya untuk menikah dengan Haris dan merawat keponakannya atau menerima lamaran lelaki yang dia cintai?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665655255_gooddreamer_PicsArt_10-09-09.55.35.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 17:27:17",
        created_at: "2022-10-13T10:00:55.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-12-19 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: true,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 39,
        novel_price: 29,
        novel_uri: "godaan-istri-kedua-X60",
        novel_title: "Godaan Istri Kedua",
        novel_sinopsis:
          "Beberapa jam setelah menikah dengan Bustan, Bia baru tahu bahwa ternyata suaminya itu sudah memiliki istri. Dan belakangan baru diketahui bahwa pria itu ternyata adalah tokoh mafia yang berkedok sebagai pegawai swasta. Mirisnya, Bia hanya dijadikan alat untuk mesin penghasil keturunan bagi Bustan mengingat istri pertama Bustan dinyatakan mandul. Bia tetap harus menjalankan perannya sebagai istri Bustan sebagaimana mestinya meski berbagai tekanan terus menyerangnya.  Setahap demi setahap, Bia mulai melakukan trik untuk memenangkan segalanya.  Ia harus bermain cantik dengan trik yang menarik.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665652165_gooddreamer_PicsArt_10-10-01.39.37.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 16:37:14",
        created_at: "2022-10-13T09:09:25.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-14 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 4,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 38,
        novel_price: 29,
        novel_uri: "psst-were-married-vUr",
        novel_title: "Psst! We’re Married",
        novel_sinopsis:
          "Lulus kuliah tepat waktu dan mendapatkan pekerjaan bagus adalah impian Jingga. Namun, sebuah lamaran yang diterima tanpa sepengetahuannya seketika langsung meruntuhkan angan dan mimpinya. Ibunya menyetujui lamaran dari seorang laki-laki yang berlandaskan hutang budi di masa lalu.\n\tYang menjadi masalah adalah Jingga sama sekali tak tahu laki-laki macam apa yang akan menikahinya. Mau menolak pun tak bisa. Ibunya sakit dan menginkan ada yang menjaga sang putri setelah dirinya tiada nanti. Tapi, hatinya sudah menjadi milik orang lain, meskipun hanya sebatas cinta bertepuk sebelah tangan.\n“Bapak kenapa ngebet banget nikah sama saya, sih?” tanya Jingga penasaran. “Kalau saya bilang punya pacar gimana?”\n“Memangnya kamu benar punya?” balas laki- laki yang duduk di hadapannya. “Kalau kamu punya, kenapa terima lamarannya?”\n“Ada, kok!” Jingga tak mau kalah. \n“Saya nggak peduli. Selesaikan hubungan kamu dengan siapapun itu.”",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665650404_gooddreamer_IMG-20221011-WA0064.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 16:12:52",
        created_at: "2022-10-13T08:40:04.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-14 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 4,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 37,
        novel_price: 29,
        novel_uri: "unforgettable-love-YDH",
        novel_title: "Unforgettable Love",
        novel_sinopsis:
          "Hanan, dan Icha adalah tokoh utama yang sama-sama memiliki trauma masa lalu. keduanya memiliki\nmasalah yang saling terikat. Namun, besarnya tekanan masalah yang dihadapi keduanya membuat\nmereka melupakan banyak hal yang sesungguhya menjadi alasan mengapa rasa diantara mereka begitu\nkuat untuk tetap bersama, meski seringkali terlihat tidak sejalan. Hanan benar-benar melupakan sosok\nIcha di masa lalunya, begitu juga Icha yang tidak pernah sadar bahwa Hanan adalah sosok yang selalu\nmenolongnya sejak dulu.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665649374_gooddreamer_image001.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 16:15:37",
        created_at: "2022-10-13T08:22:55.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-14 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 36,
        novel_price: 29,
        novel_uri: "luka-di-jalan-surga-ujV",
        novel_title: "LUKA DI JALAN SURGA",
        novel_sinopsis:
          "Apa jadinya kalau mantan terindah tiba-tiba datang menghampiri rumah tangga\nyang sedang retak karena belum juga dikaruniai anak? Kendra jadi tergoda untuk\nmenjalin lagi asmara semasa SMA yang sempat kandas. Dosa itu terasa nikmat\nbagaikan di surga ketika bersama Alissa, cinta lama yang tak pernah mati. Kendra\nmakin lupa pada istri sahnya.\nMaura yang sangat mencintai sang suami, tetap bertahan di atas luka yang\nmakin lama makin menganga. Meski tidak dihargai dan terus diperlakukan buruk, dia\nmasih terus bertahan. Cinta memang membuat manusia menjadi buta, juga tuli pada\nsiapa pun yang menasihati.\nApakah selamanya harus menderita? Maura punya caranya sendiri!",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665649025_gooddreamer_jpg_20221007_205040_0000(1).jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 15:46:51",
        created_at: "2022-10-13T08:17:05.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 35,
        novel_price: 29,
        novel_uri: "bintang-milik-angkasa-HQb",
        novel_title: "Bintang Milik Angkasa",
        novel_sinopsis:
          "“Dalam dua bulan, gue pastikan dapatin Bintang. Mulai hari ini sampai dua bulan yang akan datang, gue pastikan gue dan Bintang akan berpacaran,” ucap Angkasa. \n“Kalau lo berhasil dapatin Bintang dalam dua bulan, saham Adiyaksa Group dua puluh lima persen akan gue berikan ke lo. Kalau lo gagal, mobil sport milik lo jadi milik gue,” ucap Sean. \n“Deal,” jawab Angkasa menjabat tangan Sean dengan penuh keyakinan. \nAngkasa Putra, seorang player sejati dan hidup dalam gemerlap kesenangan dunia malam, kini siap berjuang mendapatkan hati seorang gadis yang menarik perhatiannya. Gadis yang sama yang sudah menyebutnya penjahat kelamin.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665645866_gooddreamer_IMG-20221010-WA0092.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 15:37:29",
        created_at: "2022-10-13T07:24:26.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-14 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 2,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 22,
        novel_price: 29,
        novel_uri: "mendadak-indigo-pY7",
        novel_title: "Mendadak Indigo",
        novel_sinopsis:
          "Tiba-tiba dua orang polisi datang ke kamar kos ku. Mereka berdua mengatakan bahwa Mitha\ntelah hilang sebulan yang lalu. Aku menganggap itu hanya sebagai prank terbesar abad ini karena\nbaru beberapa jam lalu aku baru saja meninggalkan gadis itu di kamar kosnya. Tapi, pembuktian ini\nberakhir membingungkan.\nKamar kos Mitha memang tergembok, tapi begitu pintu kamar itu terbuka paksa, barangku\nyang kutinggal tadi pagi masih dalam kamar terkunci itu. Aku masih tak percaya tentang informasi\npolisi itu, tapi ketika jam janji temu tiba, gadis itu memang tak muncul. Belum selesai aku meredam\nnalar yang sedang tertabrak-tabrak ini, keanehan-keanehan beruntun muncul.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665640025_gooddreamer_WhatsApp-Image-2022-10-08-at-13.31.54.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 13:49:23",
        created_at: "2022-10-13T05:47:06.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 12,
            category_name: "Paranormal Urban",
            created_at: "2022-10-16T12:53:54.000000Z",
            updated_at: "2022-10-16T12:53:54.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 89,
        novel_price: 29,
        novel_uri: "noda-pernikahan-l40",
        novel_title: "Noda Pernikahan",
        novel_sinopsis:
          "&quot;MAS LANGIT! Aku tunggu duda mu.&quot; Teriakan dari gadis bernama Dora yang\nmembuat Langit menghela nafas kasar tidak lupa dengan sorot mata tajam. Gadis gila dan\nidiot yang selalu lantang menyatakan cinta kepada Langit, padahal jelas-jelas gadis itu\ntahu kalau Langit sudah memiliki istri yang cantik.\nGadis dengan potongan rambut Bob yang bernama Dora Ariestia itu sukses\nmembuat hari-hari Langit menjadi kacau dan berantakan. Hubungan dengan Risa sang\nistri pun pasang surut, pernikahan yang mereka jalani selama 4 tahun kian hari kian\ngersang, ditambah permasalahan restu keluarga Langit membuat rumah tangga itu\nperlahan kehilangan pondasinya.\nMampukah Risa mempertahankan rumah tangganya Bersama Langit?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1666058143_gooddreamer_IMG-20221017-WA0094.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-18 09:27:10",
        created_at: "2022-10-18T01:55:43.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 90,
        novel_price: 29,
        novel_uri: "setulus-cinta-angkasa-yyR",
        novel_title: "Setulus Cinta Angkasa",
        novel_sinopsis:
          "Bermula dari kutukan yang diucapkan Helena pada seorang pria dewasa, tampan dan kaya raya. Kutukan itu ternyata  bukan sekedar kutukan. Pria itu benar-benar datang untuk menikahinya. Pria bernama Angkasa Rahardian yang merupakan seorang pengusaha muda. Menolak pun tak ada gunanya, sebab kedua orang tua Helena malah menerima dengan tangan terbuka lamaran Angkasa. Pada akhirnya mereka menikah setelah keduanya berdiskusi dan mencapai kesepakatan.  Setelah menikah, justru Angkasa lah yang memperkenalkan getaran cinta untuk pertama kalinya pada Helena. Helena seolah terjebak pada situasi rumit hingga sebuah rahasia besar terbongkar dan membuat semuanya berantakan. Pernikahan mereka pun terancam bubar.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1666068720_gooddreamer_PicsArt_10-14-11.22.02.jpg",
        novel_rating: 5,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-18 12:44:27",
        created_at: "2022-10-18T04:52:00.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-12-03 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: true,
        listed: true,
        total_purchased: 3,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 91,
        novel_price: 29,
        novel_uri: "terpaksa-menikahi-dosen-jutek-UeD",
        novel_title: "TERPAKSA MENIKAHI DOSEN JUTEK",
        novel_sinopsis:
          "Aurelia harus menerima nasib dijodohkan oleh orang tuanya untuk membalas budi. Dia tidak\nmenyangka jika lelaki yang akan menjadi calon suaminya adalah dosen di kampusnya yang\nsangat ia benci. Sejak memutuskan untuk menerima pernikahan ini rumah tangga mereka\nsering ditimpa berbagai masalah. Mulai dari hadirnya seseorang yang pernah membuat trauma\ndalam hidup Shakila di masa lalu. Atau kedatangan mantan Alvin yang ingin kembali menjalin\ncinta dengan pria itu. Apakah Shakila dan Alvin bisa menjalani pernikahan ini?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1666072704_gooddreamer_IMG-20221018-WA0010.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-18 13:21:28",
        created_at: "2022-10-18T05:58:25.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    content_name: "Eksklusif",
    type: 1,
    active: 1,
    created_at: "2022-09-19T18:52:00.000000Z",
    updated_at: "2022-09-19T18:52:00.000000Z",
    novels: [
      {
        id: 40,
        novel_price: 29,
        novel_uri: "lara-hati-rayna-zgV",
        novel_title: "Lara Hati Rayna",
        novel_sinopsis:
          "Rayna Shakila sejak kelahirannya ke dunia ia belum pernah mendapatkan kasih sayang dari kedua orang\ntuanya dan adiknya. Ia hanya mendapatkan kasih sayang dari ibu angkatnya, yang bekerja sebagai\nasisten rumah tangga di rumahnya.\nSampai Rayna dewasa, kedua hati orang tua dan adiknya sama sekali belum terbuka menyayanginya.\nMalah ketiganya semakin menjadi-jadi saat menyakiti hatinya, dan menganggap Rayna sebagai\npembantu di rumahnya sendiri.\nKehidupan Rayna sedikit lebih baik, saat Rayna bertemu dengan pria bernama Renandra tulus mencintai\nRayna. Namun, siapa sangka adiknya bernama Mili juga menaruh hati pada Renandra. Dengan segala\ncara, bahkan Mili mendapatkan bantuan kedua orang tuanya mendapatkan hati Renandra.\nTentu saja Mili menggunakan rencana licik, agar hubungan Rayna dan Renandra hancur. Mampukah\nRenandra bisa menjaga hatinya, dan selalu melindungi Rayna? Ataukah Renandra dengan mudah masuk\nperangkap Mili.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665652753_gooddreamer_FB_IMG_1665414929782.jpg",
        novel_rating: 5,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 17:48:19",
        created_at: "2022-10-13T09:19:13.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-19 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 4,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 41,
        novel_price: 29,
        novel_uri: "menikah-dengan-om-mantan-QeU",
        novel_title: "Menikah Dengan Om Mantan",
        novel_sinopsis:
          '"Bantu Saya, Kira. Menikahlah dengan Saya, maka semuanya akan aman!" ucap seorang pria dengan tinggi tubuh hampir mencapai 180cm, berusia 32 tahun, dan berprofesi sebagai Sutradara sekaligus Produser film. Di depan seorang gadis berusia 22 tahun berwajah blasteran Indonesia-Rusia.\nGadis itu tercengang mendengar pria yang tak lain adalah, calon tunangannya yang dia tinggalkan di malam pertunangan justru kembali melamarnya.\n"Sebenarnya, kamu sedang melamarku, atau mengancamku?" tanyanya.\n"Dua-duanya," ucap pria itu, kemudian tersenyum penuh maksud sehingga menampakan lesung pipi di kedua pipinya.\nGadis itu memutar bola matanya.\nBagaimana mungkin dia yang susah payah melarikan diri dari pertunangan, lantas mau menikah dengan pria itu?\nYa, sebelumnya dia dijodohkan dengan pria yang kini ada di hadapannya. Namun, dia melarikan diri di malam pertunangan dan justru menemui kekasihnya.\nSayangnya, pria itu telah menemukannya dan mengetahui apa yang dia lakukan. Pria itu bahkan mengancam akan memberitahukan perbuatannya pada maminya.\nLantas, bagaimana jadinya jika dia benar-benar menikah dengan pria itu? Akankah dia bertahan setelah tahu tujuan pria itu menikahinya?',
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665652756_gooddreamer_unnamed.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 16:55:47",
        created_at: "2022-10-13T09:19:16.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-20 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 3,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 42,
        novel_price: 29,
        novel_uri: "toxic-boyfriend-DuV",
        novel_title: "Toxic Boyfriend",
        novel_sinopsis:
          "Jalinan cinta Bianca dan Titus kandas dengan kehadiran orang ketiga. Di saat dia bangkit untuk mencoba melupakan luka hatinya, muncul Askara dengan segala kesempurnaannya. Dan benih-benih cinta di antara mereka pun tumbuh. Akan tetapi, ketika keduanya mulai merajut kasih, Titus kembali hadir di antara mereka. Bukan itu saja, kehadiran Marcel yang merupakan teman masa kecil Bianca dan akan dijodohkan dengannya, membuat Bianca dalam dilema. \nBianca merasa dunianya runtuh untuk kedua kali ketika dia dinyatakan positif hamil. Sementara untuk menerima permintaan ibunya, yaitu menikah dengan Marcel, itu tidak mungkin dengan kondisinya saat itu. Untuk meminta pertanggungjawaban Titus, juga tidak mungkin. Terlebih Titus sudah bersama dengan gadis lain.\n\nDi tengah dilema yang mendera, Bianca bertemu dengan seorang siswa SMA. Dia yang menyelamatkan dirinya ketika hampir tertabrak mobil. Naufal namanya, yang tidak lain adalah adik sepupu Askara. Dari Naufal, Bianca belajar untuk berbagi. Dia bahkan menerima saran Naufal untuk menerima Askara menjadi kekasihnya.\nApakah Askara akan tetap menerima dan mencintai Bianca setelah mengetahui kalau Bianca telah ternoda? Bagaimana dengan Marcel? Apakah dia akan menerima perjodohannya dengan Bianca, atau akan pergi meninggalkan Bianca seperti halnya Titus?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665654390_gooddreamer_IMG-20221009-WA0004.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 17:22:10",
        created_at: "2022-10-13T09:46:30.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-15 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 2,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 43,
        novel_price: 29,
        novel_uri: "ku-temukan-cinta-dalam-sujudku-bGW",
        novel_title: "Ku Temukan Cinta Dalam Sujudku.",
        novel_sinopsis:
          "Bola mata jernih dan indah milik gadis manis bernama Aqila itu terlihat berkaca-kaca saat menyaksikan adik kesayangannya bersanding dengan lelaki yang lebih dulu melamarnya..\nSeminggu yang lalu, Aqila di lamar oleh kekasih yang dicintai nya yaitu, Haris. Entah apa yang terjadi sehingga yang duduk di pelaminan itu bukan dirinya melainkan sang adik tercinta.\nTiga tahun berlalu, Haris kembali melamar Aqila  disaat dia sudah di lamar   oleh pengusaha muda yang tampan dan bijak sana bernama Nazriel Al-Fatih.\nAqila dilanda dilema yang hebat saat ia harus mempertimbangkan permintaan sang adik tercinta untuk menikah dengan Haris dan merawat anaknya sedangkan pada saat ini, hatinya sudah terpaut pada sosok Nazriel.\nAkankah Aqila menuruti permintaan adik tercinta nya untuk menikah dengan Haris dan merawat keponakannya atau menerima lamaran lelaki yang dia cintai?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665655255_gooddreamer_PicsArt_10-09-09.55.35.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 17:27:17",
        created_at: "2022-10-13T10:00:55.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-12-19 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: true,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    content_name: "Novel Andalan",
    type: 1,
    active: 1,
    created_at: "2022-09-26T09:54:46.000000Z",
    updated_at: "2022-09-26T09:54:46.000000Z",
    novels: [
      {
        id: 37,
        novel_price: 29,
        novel_uri: "unforgettable-love-YDH",
        novel_title: "Unforgettable Love",
        novel_sinopsis:
          "Hanan, dan Icha adalah tokoh utama yang sama-sama memiliki trauma masa lalu. keduanya memiliki\nmasalah yang saling terikat. Namun, besarnya tekanan masalah yang dihadapi keduanya membuat\nmereka melupakan banyak hal yang sesungguhya menjadi alasan mengapa rasa diantara mereka begitu\nkuat untuk tetap bersama, meski seringkali terlihat tidak sejalan. Hanan benar-benar melupakan sosok\nIcha di masa lalunya, begitu juga Icha yang tidak pernah sadar bahwa Hanan adalah sosok yang selalu\nmenolongnya sejak dulu.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665649374_gooddreamer_image001.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 16:15:37",
        created_at: "2022-10-13T08:22:55.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-14 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 17,
        novel_price: 29,
        novel_uri: "lets-talk-about-everything-again-INw",
        novel_title: "Let’s Talk About Everything Again",
        novel_sinopsis:
          "Shanien Adyatma dan Reksa Soedjatkimo adalah pasangan suami istri yang bercerai tiga\ntahun lalu. Ketidaksiapan mereka dalam menghadapi kehidupan pernikahan dan hadirnya\norang dari masa lalu Reksa membuat pernikahan itu mencapai batas usai. Namun, tidak\ndapat dipungkiri bahwa rindu dan cinta masih membekas di antara keduanya, walaupun\ntidak pernah sempat terucapkan bahkan sampai di hari mereka bercerai.\nTiga tahun lamanya Shanien mengurus putri semata wayangnya hingga tiba-tiba, Reksa hadir\nkembali menawarkan rasa baru di hati Shanien. Dengan pikiran yang lebih dewasa, mental\nyang lebih siap, juga sikap yang tegas, akankah mereka bisa kemblai lagi menata hati yang\npernah reta? Atau memang mereka sudah usai?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665630943_gooddreamer_IMG_20221007_172510.jpg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 13:10:21",
        created_at: "2022-10-13T03:15:43.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-16 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 5,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 15,
        novel_price: 29,
        novel_uri: "cinderella-tanpa-nama-tJY",
        novel_title: "Cinderella Tanpa Nama",
        novel_sinopsis:
          "Naknak adalah seorang gadis kecil yang dibuang dan tidak diinginkan, hingga akhirnya dia\nberjumpa dengan seorang ibu adopsi dan memberinya nama. Penyesalan ibu kandungnya\nmembuat dia harus menemukan Naknak kembali. Dia akhirnya berjumpa dengan Sonia dan\nKiki. Tetapi ibu kandungnya bingung memilih di antara Sonia dan Kiki yang mana\nsebenarnya Naknak.\n\nNaknak merasa nasibnya seperti Cinderella, hanya saja Cinderella sengsara karena ibu\ntirinya. Sementara Naknak menderita karena ibu kandungnya.\n\nSebenarnya Naknak adalah gadis yang kuat, tetapi di dalam perjuangan hidupnya Naknak\nmasih belum bisa menerima kehadiran ibunya, Audy. Ketika dia akhirnya dapat menerima\nibunya, hatinya kembali terhempas setelah mengetahui alasan dia terlahir ke dunia ini. Hati\nNaknak kembali terluka, hingga akhirnya seorang pangeran datang menolong dan menarik\ndia keluar dari jurang yang dalam.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665420707_gooddreamer_WhatsApp-Image-2022-10-07-at-20.35.19.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-11 01:26:06",
        created_at: "2022-10-10T16:51:47.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: "2022-11-20 00:00:00",
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: true,
        total_purchased: 9,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 9,
            category_name: "Action",
            created_at: "2022-10-16T12:52:55.000000Z",
            updated_at: "2022-10-16T12:52:55.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 22,
        novel_price: 29,
        novel_uri: "mendadak-indigo-pY7",
        novel_title: "Mendadak Indigo",
        novel_sinopsis:
          "Tiba-tiba dua orang polisi datang ke kamar kos ku. Mereka berdua mengatakan bahwa Mitha\ntelah hilang sebulan yang lalu. Aku menganggap itu hanya sebagai prank terbesar abad ini karena\nbaru beberapa jam lalu aku baru saja meninggalkan gadis itu di kamar kosnya. Tapi, pembuktian ini\nberakhir membingungkan.\nKamar kos Mitha memang tergembok, tapi begitu pintu kamar itu terbuka paksa, barangku\nyang kutinggal tadi pagi masih dalam kamar terkunci itu. Aku masih tak percaya tentang informasi\npolisi itu, tapi ketika jam janji temu tiba, gadis itu memang tak muncul. Belum selesai aku meredam\nnalar yang sedang tertabrak-tabrak ini, keanehan-keanehan beruntun muncul.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665640025_gooddreamer_WhatsApp-Image-2022-10-08-at-13.31.54.jpeg",
        novel_rating: 4,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-13 13:49:23",
        created_at: "2022-10-13T05:47:06.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 12,
            category_name: "Paranormal Urban",
            created_at: "2022-10-16T12:53:54.000000Z",
            updated_at: "2022-10-16T12:53:54.000000Z",
            novels_count: null,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    content_name: "On Going Novel",
    type: 2,
    active: 1,
    created_at: "2022-10-13T13:07:09.000000Z",
    updated_at: "2022-10-13T13:07:09.000000Z",
    novels: [
      {
        id: 48,
        novel_price: 29,
        novel_uri: "cinta-kedua-RNL",
        novel_title: "Cinta Kedua",
        novel_sinopsis:
          "Setiap wanita pasti memimpikan sebuah keluarga kecil yang bahagia. Memiliki suami yang dapat\nmenerima segala kekurangan dan kelebihan. Begitu juga dengan Nanda, yang ingin memiliki pasangan\nsejati baik di dunia maupun di akhirat kelak.\nTapi kenyataan tidak seindah angan Nanda. Prahara rumah tangga yang menguras air mata tengah\nmengujinya. Dimana sang suami tidak mengakui darah dagingnya sendiri. Menorehkan luka pada batin\nNanda begitu dalam. Dapatkah Nanda mempertahankan keutuhan rumah tangganya? Akankah Nanda\nmenyerah dan memilih untuk pergi demi masa depan putranya?\n“Sampai kapanpun aku tidak akan pernah mengakui anak penyakitan itu sebagai anakku.” Arya Wijaya\n“Aku bersumpah demi hidup putraku! Aku tidak akan memaafkanmu meskipun kau menangis darah di\ndepanku.” Nanda Prisya\n“Memiliki Arka bukanlah hal yang memalukan bagiku. Tapi, Arka adalah malaikat kecil yang\nmengajarkanku untuk tetap tegar dan tidak menyerah.” Rian Adiguna.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665710319_gooddreamer_PicsArt_10-09-10.09.58.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 08:56:27",
        created_at: "2022-10-14T01:18:39.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 2,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 49,
        novel_price: 29,
        novel_uri: "renjani-fm-KEt",
        novel_title: "Renjani FM",
        novel_sinopsis:
          "Digosipkan kabur ke Semarang karena hamil dan melahirkan seorang bayi laki-laki. Membuat Fatya\nSachikirani jadi buah bibir di kampung. Pelopornya adalah Ibu Nindi Arum, si bigos di kampung.\nSemua info tak ada yang terlewat dari tatapan tajamnya.\n\nPekerjaan Tya sebagai penyiar radio malam, membuat Nindi berpikir negatif tentang gadis itu.\nPadahal, Renjani FM jadi saksi kalau tak ada hal buruk yang dilakukan gadis bertubuh gemuk\nitu.\n\nSampai hal yang tak pernah Nindi duga terjadi. Nindi harus dihadapkan pada kenyataan kalau Tya\nadalah kekasih Yuga Sebastian Manendra.\n\nApa yang terjadi pada Nindi setelah mengetahui gadis yang selalu ia gosipkan adalah calon\nmenantunya?\n\nApakah Nindi akan menentang hubungan Yuga dan Tya?\n\nLalu bagaimana cara Yuga dan Tya meyakinkan Nindi tentang hubungan mereka?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665711947_gooddreamer_PicsArt_10-10-05.27.56.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 13:36:38",
        created_at: "2022-10-14T01:45:48.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 50,
        novel_price: 29,
        novel_uri: "cinta-sudah-lewat-Qku",
        novel_title: "Cinta Sudah Lewat",
        novel_sinopsis:
          "Dengan matanya sendiri Sandra akhirnya tau jika selama ini Sean kekasihnya telah berselingkuh\ndarinya, tentu dia sangat kecewa namun mau tidak mau dia harus tetap menunjukkan pada\nSean jika dia bukan gadis yang akan tumbang karena perselingkuhan itu.\nMenyesal sudah pasti, tapi akhirnya keputusan Sandra yang bulat telah membuatnya menjadi\nwanita yang lebih tegar dan membuat Sean menyesal.\nMampukan Sandra membalas sakit hatinya dengan pembuktiannya? Dan apakah Sandra mau\nkembali ke pelukan Sean yang tengil dan ketus?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665712936_gooddreamer_PicsArt_10-09-10.18.43.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 11:28:00",
        created_at: "2022-10-14T02:02:16.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 10,
            category_name: "New Adult",
            created_at: "2022-10-16T12:53:12.000000Z",
            updated_at: "2022-10-16T12:53:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 51,
        novel_price: 29,
        novel_uri: "rahim-sewaan-tuan-muda-DxX",
        novel_title: "Rahim Sewaan Tuan Muda",
        novel_sinopsis:
          "Danela Lingga Rumika, gadis polos dan super jenius itu dipaksa untuk menjadi ibu rahim di usia yang masih 16 tahun oleh Mamanya dengan bayaran lima milyar. \n\nHanya dalam satu malam, dia telah mengubah banyak hal dalam hidupnya. Kecantikan dan juga kepolosannya, membuat Regan yang dikenal sebagai pria yang dingin, yang tidak pernah mau kenal atau menyentuh mahluk yang namanya perempuan akhirnya bisa tidur dengannya.\n\nCinta satu malam itu membuat Danela melahirkan anak kembar. Satu dalam keadaan sehat dan diambil oleh pria yang sudah membayarnya, satu anak yang lain divonis meninggal oleh dokter dan pihak rumah sakit sudah mempersiapkan pemakamannya. Siapa sangka, dalam pelukan Danela, bayi yang sudah tidak benapas itu bisa menggerakkan matanya dan akhirnya bisa hidup dalam pengasuhannya.\n\nApakah Danela bisa menyembunyikan keberadaan anak itu dari keluarganya yang sebenarnya?  Apakah air mata Danela bisa menyatukan dirinya dengan ayah biologis anak yang ada dalam pengasuhannya?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665713974_gooddreamer_COVER-PESANAN1.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 09:52:31",
        created_at: "2022-10-14T02:17:03.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 52,
        novel_price: 29,
        novel_uri: "pendekar-rajawali-putih-gdv",
        novel_title: "Pendekar Rajawali Putih",
        novel_sinopsis:
          "Danu terlahir sebagai seorang Putra Mahkota Kerajaan Salaka Nagara. Ayahandanya\nyang bernama Raja Dewawarman di khianati oleh Patih Kerajaan sendiri. Dengan meminta\nbantuan kepada beberapa Padepokan silat aliran hitam beserta Prajurit yang mendukung\npemberontakannya, Patih Kosambi menyerang kerajaan dan membunuh Raja Dewawarman\ndengan sangat keji. Kekuasaan di ambil alih bersama dengan Pendukungnya yang sama-sama\nserakah. Saat Pemberontakan terjadi Permaisuri Andini dan Putra Mahkota di ungsikan dari\nkerajaan lalu di hadang oleh Prajurit pemberontak sehingga terjadi pertarungan.\nPermaisuri menyerahkan Danu kepada seorang Dayang kepercayaannya bernama\nArimbi. Saat dalam pelarian tanpa Arah Dayang itu di tangkap oleh Prajurit penghianat dan di\nselamtkan oleh seorang Pendekar sakti lalu di bawa ke lembah Rajawali. Danu di latih oleh\nLima orang sakti yang mengangkatnya sebagai Murid. Kelima Gurunya itu memiliki ilmu yang\nberbeda-beda. Masing-masing dengan kelebihan dan kekurangan sendiri-sendiri. Hingga Danu\nberusia tujuh belas Tahun dan menguasai seluruh Kesaktian Mereka. Pada saat itulah Danu\nturun gunung dan berpetualang membela kebenaran dan menumpas kejahatan serta\nmenuntut Haknya di kerajaan Salaka Nagara. Akankah Danu berhasil mengambil Haknya\nsebagai Raja di Kerajaan? Silahkan baca Novel Pendekar Rajawali putih dan menjadi saksi\nlahirnya seorang pendekar konyol di dunia Persilatan.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665715474_gooddreamer_IMG-20221012-WA0030.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 10:17:30",
        created_at: "2022-10-14T02:44:34.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 2,
            category_name: "Fantasi",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 9,
            category_name: "Action",
            created_at: "2022-10-16T12:52:55.000000Z",
            updated_at: "2022-10-16T12:52:55.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 53,
        novel_price: 29,
        novel_uri: "kampung-janda-7qA",
        novel_title: "KAMPUNG JANDA",
        novel_sinopsis:
          "Alesha Zahra adalah gadis berusia 21 tahun. Cantik, cerdas, periang, pemberani dan tidak percaya akan hal-hal mistis. Ibunya adalah wanita shalihah yang menginginkan Alesha Zahra agar menikah dengan pria saleh anak sahabatnya yang bernama Yusuf.\n\n    Untuk menolak perjodohan yang direncanakan oleh ibunya, Alesha Zahra bertengkar dengan Yusuf untuk meninggal kesan buruk, berharap Yusuf tidak menyetujui perjodohan itu. \n\n     Alesha Zahra bersama Feby dan Johan diam-diam berwisata  bersama di daerah Bukit Misteri. Ketika melewati Titi gantung tua, terjadi kecelakaan, tiba-tiba Titi gantung roboh, saat bersamaan arus air pun naik dengan derasnya, untung ada rakit bambu yang hanyut, Alesha Zahra beserta teman-teman menaiki rakit dan terhanyut hingga ke hilir sungai.\n\n     Mereka akhirnya terdampar di kampung janda. Sebuah kampung terpencil yang terletak di balik Bukit Misteri, hanya dihuni oleh para janda-janda cantik, seksi tiada menua. Banyak keanehan yang terjadi di sana, tiada sesuai dengan akal pemikiran Alesha Zahra. Rasa penasarannya terhadap kampung janda membuat mereka menghadapi berbagai masalah, bahkan hampir merenggut nyawanya dan teman-teman.\n\n      Mampukah Alesha keluar dengan selamat dari kampung itu?",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665716086_gooddreamer_COVER-OKE.jpeg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 10:21:35",
        created_at: "2022-10-14T02:54:46.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 1,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
          {
            id: 9,
            category_name: "Action",
            created_at: "2022-10-16T12:52:55.000000Z",
            updated_at: "2022-10-16T12:52:55.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 54,
        novel_price: 29,
        novel_uri: "skenario-hidup-miss-nadira-2JE",
        novel_title: "Skenario Hidup Miss Nadira",
        novel_sinopsis:
          "Anak itu pun melangkah, tunggu ..., apa dia masih layak dipanggil anak? Usianya dua puluh\ntahun, paling tua di antara temannya. Ini seperti dia adalah orang dewasa yang sedang\nmemakai seragam anak SMA. Astaga.\n***\n“Bagaimana bisa?” selaku segera.\n“Apanya?” tanyanya tak acuh.\n“Menjadi anak SMA di usia dua puluh tahun,” tukasku. Menelisik wajahnya yang sudah ditumbuhi\nbulu-bulu halus di bagian pelipis dan dagu. Benar-benar tidak pantas menjadi siswa SMA.\nDevan menyandarkan punggungnya, lalu melipat kedua tangan di dada. “Mungkin ... itu karena\norang-orang di sekolah ini terlalu menyayangi saya, jadi mereka tidak membiarkan saya pergi\ndari sini,” jawabnya.\nAku menaikkan satu sudut bibirku seraya berdecak. “Sudah cukup membualnya?”\n“Belum.” Devan tersenyum kecil. “Miss mau tau bualan saya selanjutnya?”\n“Apa itu?” tantangku.\nLelaki itu menarik tubuhnya hingga lebih miring ke arah meja dan kepalanya mendekat ke arahku.\n“Miss cantik, dan jantung saya berdebar cepat saat ini.”\nAku mengedipkan mata, merasa tidak mengerti dengan ucapannya. Detik berikutnya dia berdiri,\nlalu mengaitkan satu tali tas punggungnya ke bahu kanan. Pergi dari ruangan kelas tanpa\nsepatah kata pun.\n“Miss cantik, dan jantung saya berdebar cepat saat ini.”\n\nAku menggelengkan kepala mengingat ucapannya itu. Merasa sebal dengan bualannya yang entah\nke berapa puluh kali. Aku pun segera meraih tas juga buku materi di atas meja, lalu keluar dari\nkelas.\nSepanjang perjalanan pulang, aku berusaha melupakannya. Mencoba berkonsentrasi membaca\nbuku di tangan atau kadang menatap sejenak keramaian kota di sore hari. Sialnya, aku tidak\nbisa mengenyahkan ucapan anak itu. Oh, God. Ada apa dengan diriku?!",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665719876_gooddreamer_WhatsApp-Image-2022-10-14-at-10.52.29.jpeg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 10:54:20",
        created_at: "2022-10-14T03:08:51.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 55,
        novel_price: 29,
        novel_uri: "ayah-aku-salah-apa-dK6",
        novel_title: "Ayah, Aku Salah Apa?",
        novel_sinopsis:
          "Berkisah tentang perjalanan seorang wanita yang merasa tidak adil dengan perlakuan ayahnya. Dimulai dari masa kecil Ros dipaksa untuk selalu kuat dan bertanggung jawab demi keluarganya, Ros anak ke tiga dari delapan bersaduara harus berjuang menjalani hidup dalam keterbatasan ekonomi demi mencari kehidupan yang lebih layak. Namun, ketika ia mulai menjalani takdirnya, Ros harus berjibaku dengan perasaannya yang kecewa melihat perlakuan ayahnya setelah apa yang ia lakukan demi keluarganya tidak dihargai sama sekali.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665718649_gooddreamer_IMG-20221010-WA0030.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 11:11:44",
        created_at: "2022-10-14T03:37:30.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 7,
            category_name: "Horor",
            created_at: "2022-10-14T03:32:22.000000Z",
            updated_at: "2022-10-14T03:32:22.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 56,
        novel_price: 29,
        novel_uri: "hello-husband-pXy",
        novel_title: "Hello Husband!",
        novel_sinopsis:
          "Chana, harus mati setelah mengetahui perselingkuhan suaminya dengan adik tirinya saat ia tengah hamil tua. Di kurung dalam mansion tua dan seluruh keluarga mengasingkannya, dia jelas melihat bagaimana adik tirinya mengambil putra pertama yang dilahirkannya untuk disiksa hingga tiada lalu dia dipaksa menegak segelas racun untuk kematiannya. Hal yang baru dia ketahui saat tubuhnya merasakan sakit luar biasa, seluruh kesakitan dalam hidupnya telah diatur sedemikian rupa oleh suami dan adik tiri juga seluruh keluarganya. Ia dihianati oleh seluruh orang yang ia cintai hingga mati! \n\n      Merasa tak terima dan menuntut kebahagiaan juga dendam yang harus dia balaskan, dia dilahirkan kembali tepat satu bulan sebelum pernikahannya terjadi. Membatalkan pernikahan, memutuskan hubungan, membuka topeng busuk adik tirinya sampai mengungkap seluruh perselingkuhan mereka, dia juga menuntut hak atas semua yang harus dia miliki sebagai putri tertua keluarga ternama. Dalam kehidupan ini, dia berniat membalaskan dendam atas kematian putra dan setiap rasa sakit yang dia terima lengkap dengan seluruh bunga yang harus mereka terima.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665719566_gooddreamer_PicsArt_10-08-02.03.59.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 12:58:03",
        created_at: "2022-10-14T03:52:47.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
      {
        id: 57,
        novel_price: 29,
        novel_uri: "parfum-pengikat-cinta-7AL",
        novel_title: "PARFUM PENGIKAT CINTA",
        novel_sinopsis:
          "Kisah dua orang yang terpisahkan oleh jarak dan waktu. Berkat aroma parfum akhirnya\nmereka bisa kembali bersama, mengukir mimpi dan merajut asa. Sayangnya kebahagiaan\nmereka harus terusik oleh orang ketiga yang merasa iri sehingga segala cara dilakukan untuk\nmemisahkan keduanya.\n\nSeiring berjalannya waktu semua terungkap satu per satu, tapi sayangnya sudah terlambat.",
        novel_cover:
          "https://latte-api.gooddreamer.id/storage/novels/1665720193_gooddreamer_IMG-20221012-WA0023.jpg",
        novel_rating: 0,
        active: 1,
        status: 2,
        extend_status: 0,
        bundle: 0,
        free_chapter: 5,
        published_at: "2022-10-14 11:29:47",
        created_at: "2022-10-14T04:03:14.000000Z",
        updated_at: "2022-11-19T11:52:11.000000Z",
        expired_at: null,
        chapters_count: null,
        readers_count: null,
        word_count: 0,
        purchased: false,
        listed: false,
        total_purchased: 0,
        categories: [
          {
            id: 1,
            category_name: "Romansa",
            created_at: "2022-08-20T11:01:12.000000Z",
            updated_at: "2022-08-20T11:01:12.000000Z",
            novels_count: null,
          },
        ],
      },
    ],
  },
];
