import type { ContentType } from "types/NovelTypes";

/* eslint-disable max-len */
export const dataContents: ContentType[] = [
  {
    uuid: "c95a2864-2cba-4528-8f38-22559d23d293",
    content_name: "nihil",
    content_sort: 1,
    content_icon_path: "https://via.placeholder.com/18x18",
    content_icon_filename: "https://via.placeholder.com/18x18",
    content_slug: "nihil",
    type: 1,
    active: 1,
    novel: [
      {
        uuid: "850f1bf6-7c34-4499-913b-6748681f38d5",
        title: "Deleniti a accusamus libero id rerum.",
        author: "Prince Columbus Frami",
        sinopsis: "Est et itaque repudiandae doloribus doloremque.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "fb7d65e7-726f-482d-8de8-5481a1ace6c8",
        title: "Et est impedit ex quia dolorum.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Qui quaerat omnis sit sed voluptas. Rerum totam maxime eos reprehenderit blanditiis. Non non eum vero cumque veniam. Sunt sit sint quo qui voluptatem. Similique dignissimos aliquam omnis veritatis hic. Ducimus voluptatem sint est eum at.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f7863",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f78631",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f78632",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f78633",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f78634",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f78635",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
    ],
  },
  {
    uuid: "a133b226-6fcc-4020-9d9b-1db461d0614b",
    content_name: "vero",
    content_sort: 1,
    content_icon_path: "https://via.placeholder.com/18x18",
    content_icon_filename: "https://via.placeholder.com/18x18",
    content_slug: "vero",
    type: 2,
    active: 1,
    novel: [
      {
        uuid: "850f1bf6-7c34-4499-913b-6748681f38d5",
        title: "Deleniti a accusamus libero id rerum.",
        author: "Prince Columbus Frami",
        sinopsis: "Est et itaque repudiandae doloribus doloremque.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "fb7d65e7-726f-482d-8de8-5481a1ace6c8",
        title: "Et est impedit ex quia dolorum.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Qui quaerat omnis sit sed voluptas. Rerum totam maxime eos reprehenderit blanditiis. Non non eum vero cumque veniam. Sunt sit sint quo qui voluptatem. Similique dignissimos aliquam omnis veritatis hic. Ducimus voluptatem sint est eum at.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f7863",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
    ],
  },
  {
    uuid: "e2b751c3-1ee5-4df5-8d59-b7e2da2fea4d",
    content_name: "sint",
    content_sort: 1,
    content_icon_path: "https://via.placeholder.com/18x18",
    content_icon_filename: "https://via.placeholder.com/18x18",
    content_slug: "sint",
    type: 2,
    active: 1,
    novel: [
      {
        uuid: "850f1bf6-7c34-4499-913b-6748681f38d5",
        title: "Deleniti a accusamus libero id rerum.",
        author: "Prince Columbus Frami",
        sinopsis: "Est et itaque repudiandae doloribus doloremque.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "fb7d65e7-726f-482d-8de8-5481a1ace6c8",
        title: "Et est impedit ex quia dolorum.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Qui quaerat omnis sit sed voluptas. Rerum totam maxime eos reprehenderit blanditiis. Non non eum vero cumque veniam. Sunt sit sint quo qui voluptatem. Similique dignissimos aliquam omnis veritatis hic. Ducimus voluptatem sint est eum at.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f7863",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
    ],
  },
  {
    uuid: "fb3db31b-ba72-4920-9d35-25f5d4841aeb",
    content_name: "vel",
    content_sort: 1,
    content_icon_path: "https://via.placeholder.com/18x18",
    content_icon_filename: "https://via.placeholder.com/18x18",
    content_slug: "vel",
    type: 2,
    active: 1,
    novel: [
      {
        uuid: "850f1bf6-7c34-4499-913b-6748681f38d5",
        title: "Deleniti a accusamus libero id rerum.",
        author: "Prince Columbus Frami",
        sinopsis: "Est et itaque repudiandae doloribus doloremque.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "fb7d65e7-726f-482d-8de8-5481a1ace6c8",
        title: "Et est impedit ex quia dolorum.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Qui quaerat omnis sit sed voluptas. Rerum totam maxime eos reprehenderit blanditiis. Non non eum vero cumque veniam. Sunt sit sint quo qui voluptatem. Similique dignissimos aliquam omnis veritatis hic. Ducimus voluptatem sint est eum at.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f7863",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
    ],
  },
  {
    uuid: "78386bb0-4949-48e6-b37e-08ed73010ec5",
    content_name: "similique",
    content_sort: 1,
    content_icon_path: "https://via.placeholder.com/18x18",
    content_icon_filename: "https://via.placeholder.com/18x18",
    content_slug: "similique",
    type: 3,
    active: 1,
    novel: [
      {
        uuid: "850f1bf6-7c34-4499-913b-6748681f38d5",
        title: "Deleniti a accusamus libero id rerum.",
        author: "Prince Columbus Frami",
        sinopsis: "Est et itaque repudiandae doloribus doloremque.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "fb7d65e7-726f-482d-8de8-5481a1ace6c8",
        title: "Et est impedit ex quia dolorum.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Qui quaerat omnis sit sed voluptas. Rerum totam maxime eos reprehenderit blanditiis. Non non eum vero cumque veniam. Sunt sit sint quo qui voluptatem. Similique dignissimos aliquam omnis veritatis hic. Ducimus voluptatem sint est eum at.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
      {
        uuid: "4ada6f21-f4e1-42aa-84e0-20eb7c1f7863",
        title: "Sint quasi facilis maxime sit dolores.",
        author: "Prince Columbus Frami",
        sinopsis:
          "Id fugit ab earum nulla eaque. Enim qui expedita quo velit voluptatem. Et ut autem laudantium consequatur ut. Deserunt reiciendis quod culpa neque nihil. Numquam dolorum ut et laborum rem.",
        cover_path: "https://via.placeholder.com/140x224",
        cover_file_name: "https://via.placeholder.com/140x224",
        rating: 4.5,
        price: 45000,
        active: 1,
        status: 1,
        language: "Indonesia",
      },
    ],
  },
];
