/* eslint-disable max-len */
export const dataHighlight: any = [
  {
    id: 62,
    created_at: "2022-10-22T15:19:11.000000Z",
    updated_at: "2022-10-22T15:19:11.000000Z",
    novel: {
      id: 70,
      novel_price: 29,
      novel_uri: "madu-untuk-suamiku-74T",
      novel_title: "Madu Untuk Suamiku",
      novel_sinopsis:
        "Kartika harus mencari istri bagi suaminya, dikarenakan umurnya yang sudah tidak akan lama lagi. Dengan segala upaya dan bujuk rayu, akhirnya sang suami bersedia menikahi wanita pilihan sang istri.\n\nBagi Bram, Kartika adalah satu-satunya wanita yang ia cintai. Ia dan istri keduanya membuat sebuah perjanjian, bahwa mereka tidak akan saling menyentuh satu sama lain, tidak akan pernah saling jatuh cinta.",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665732604_gooddreamer_WhatsApp-Image-2022-10-12-at-01.14.37.jpeg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 15:13:11",
      created_at: "2022-10-14T07:30:04.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: "2022-12-03 00:00:00",
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: true,
      listed: true,
      total_purchased: 2,
    },
  },
  {
    id: 63,
    created_at: "2022-10-22T15:19:25.000000Z",
    updated_at: "2022-10-22T15:19:25.000000Z",
    novel: {
      id: 72,
      novel_price: 29,
      novel_uri: "atasan-dan-bawahan-kOz",
      novel_title: "Atasan dan Bawahan",
      novel_sinopsis:
        "Ibrahim Pradipta hanya menyukai pekerjaannya, ketika dia dipaksa menikah karena keinginan orang tuanya, pria itu melakukannya tanpa hati. Demikian juga dengan Tita Yulianti yang terpaksa harus menikah dengan Ibrahim demi melunasi hutang keluarganya, dia pun melakukan hal yang sama—menikah tanpa cinta.\n\nIbrahim dan Tita sepakat untuk merahasiakan pernikahannya dari teman-teman kantor. Mereka pasangan suami istri hanya bila di depan kedua orang tuanya.\n\nNamun, apa yang terjadi ketika keduanya merasa tertarik satu sama lain secara biologis? Bisakah mereka menjalani pernikahan tanpa adanya saling jujur soal perasaan masing-masing?",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665734819_gooddreamer_WhatsApp-Image-2022-10-12-at-00.19.04.jpeg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 15:47:29",
      created_at: "2022-10-14T08:06:59.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: "2022-12-03 00:00:00",
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: true,
      listed: true,
      total_purchased: 7,
    },
  },
  {
    id: 65,
    created_at: "2022-10-22T15:19:52.000000Z",
    updated_at: "2022-10-22T15:19:52.000000Z",
    novel: {
      id: 100,
      novel_price: 29,
      novel_uri: "no-longer-Uy1",
      novel_title: "No Longer",
      novel_sinopsis:
        "Annastasia Purnama adalah seorang mahasiswi kupu-kupu yang berkuliah demi menghindar\ndari orang tuanya yang memiliki hubungan yang kurang baik. Anna mendambakan kasih\nsayang yang sayangnya ia dapatkannya dari lelaki bernama Theo yang merupakan seorang\ncasanova.\nNamun, hidup Anna yang seenaknya berubah drastis saat bertemu dengan Keanu yang\nmerupakan asisten dosen sekaligus sahabat dari kekasihnya. Kehadiran Keanu memberikan\ndampak yang cukup banyak termasuk kepada hubungan Anna dan Theo.\nApakah Keanu mengubah hidup Anna menjadi lebih baik, atau malah sebaliknya?",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1666155973_gooddreamer_cover-no-longer---tiapurnamasetiani15-(1).jpg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-19 12:33:05",
      created_at: "2022-10-19T05:06:14.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: "2022-12-03 00:00:00",
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: true,
      listed: true,
      total_purchased: 4,
    },
  },
  {
    id: 66,
    created_at: "2022-10-22T15:20:10.000000Z",
    updated_at: "2022-10-22T15:20:10.000000Z",
    novel: {
      id: 96,
      novel_price: 29,
      novel_uri: "kidung-di-tanah-terkutuk-KPh",
      novel_title: "Kidung di Tanah Terkutuk",
      novel_sinopsis:
        "Argani tiba-tiba mendapatkan kabar jika sang nenek telah meninggal dunia pada hari Rabu, lebih\ntepatnya Selasa malam. Ia tidak pernah menyangka jika berita kematian sang nenek itu datang\nsecara mendadak, pasalnya baru saja hari kemarin ia dan sang adik menelepon sang nenek yang\nmasih terlihat bugar dan sehat.\nBeberapa waktu berselang, Argani mendapatkan sebuah tugas dari sang ibu untuk mengurusi\nsertifikat rumah sang nenek dan juga surat keterangan kematian di Jawa timur. Dan liburan sekolah\nlah menjadi kesempatan Argani untuk pergi bersama sang adik pergi ke sana. Argani juga mengajak\nkedua teman dekatnya untuk sama-sama berlibur di daerah Jawa Timur itu.\n“Tanah menika sanes lah tanah suwarga, wonten tanah menika sadayanipun mboten ngagungani\nnasib ingkang nggih. Keburukan ajeng rawuh lan ndhereki sintena ingkang napakaken\nsamparanipun lan manggen. Tanah ingkang ajeng ngasta kesengsaraan, rekaos ngantos kasedan.”\n(Di tulis dalam Bahasa Jawa)\n“Tanah ini bukanlah tanah surga, di tanah ini... Semuanya tidak memiliki nasib yang baik.\nKeburukan akan datang dan menyertai siapapun yang menginjakkan kakinya dan menetap.\nTanah yang akan membawa kesengsaraan, sengsara hingga kematian” (Arti dalam Bahasa\nIndonesia)\nItulah kalimat yang terdengar di telinga Argani ketika ia, kedua temannya beserta adik laki-lakinya\nmenginjakkan kaki di sebuah rumah besar yang telah di wariskan oleh sang nenek padanya. Kalimat\ntersebut bagaikan sebuah nyanyian yang di bisikan ke telinganya. Karena Argani tidak mengerti\nBahasa Jawa, maka ia mengabaikan suara tersebut.\nSuara yang sebenarnya adalah sebuah peringatan... Peringatan dalam bentuk sebuah Kidung, yang\nselalu berbunyi pada siapapun yang menginjakkan kakinya di tanah itu. Tanah terkutuk!",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1666147381_gooddreamer_IMG-20221010-WA0010.jpg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-19 10:09:28",
      created_at: "2022-10-19T02:43:01.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: null,
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: false,
      listed: true,
      total_purchased: 1,
    },
  },
  {
    id: 86,
    created_at: "2022-10-22T18:51:26.000000Z",
    updated_at: "2022-10-22T18:51:26.000000Z",
    novel: {
      id: 64,
      novel_price: 29,
      novel_uri: "kesatria-bumi-CCK",
      novel_title: "Kesatria Bumi",
      novel_sinopsis:
        'Lily menemukan bahwa sebagai keturunan setengah nimfa, leluhurnya, Mantica, adalah sumber dari perpecahan yang memicu kebrutalan Olimpus.\nMantica adalah nimfa paling rupawan yang bejat, menyesatkan para dewa dewi hingga mereka bertekuk lutut memujanya. \nZeus terjerat oleh pesona Mantica dan sanggup berkhianat dari Hera.\nKini Lily mengetahui alasan yang tepat, kenapa ratu Olimpus begitu membenci dirinya.\nTanpa disangka oleh siapa pun, Mantica yang terkubur di laut hitam bangkit dan menginginkan kembali kejayaannya dengan menjadi permaisuri Zeus dan menguasai dunia. \nMantica telah membelah jiwanya menjadi tiga. Satu jiwa di alam transisi, kedua dalam diri Arethusa dan ketiga dalam tubuh Lily. \nApakah kali ini Lily harus menumpas leluhurnya, demi menciptakan kedamaian di muka bumi?\n"Takdirmu adalah meruntuhkan Olimpus. Bela bumi ini dari mereka yang tidak menginginkan kita menginjak tanah yang sama dalam damai!”\nKisah ini tentang perjuangan, cinta yang tersakiti, juga persahabatan yang tiada akhir. Pahlawan adalah makhluk seperti kita, memiliki sisi lemah dan rapuh. \nHanya saja, mereka selalu punya cara untuk bangkit, menyingkirkan segala kepentingan pribadi demi menyelamatkan yang lain!\nInilah perjalanan para pembela bumi yang berjuang hingga titik darah terakhir, tanpa diketahui oleh manusia yang saat ini berusaha merusak dengan cara mereka sendiri!',
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665729376_gooddreamer_WhatsApp-Image-2022-10-11-at-22.09.55.jpeg",
      novel_rating: 4,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 14:03:31",
      created_at: "2022-10-14T06:36:17.000000Z",
      updated_at: "2022-12-07T03:14:14.000000Z",
      expired_at: "2023-01-07 00:00:00",
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: true,
      listed: true,
      total_purchased: 6,
    },
  },
  {
    id: 87,
    created_at: "2022-10-22T18:51:35.000000Z",
    updated_at: "2022-10-22T18:51:35.000000Z",
    novel: {
      id: 65,
      novel_price: 29,
      novel_uri: "pesan-pasien-tak-kasat-mata-4aP",
      novel_title: "Pesan Pasien Tak Kasat Mata",
      novel_sinopsis:
        "Setiap insan manusia yang dilahirkan pasti memiliki kekurangan. Tak terkecuali aku—Bian Alvaro.\nDilahirkan dengan kondisi ANOSMIA (Kehilangan indera penciuman secara total atau sebagian)\nTak kusangka, kekurangan yang membuatku sangat berbeda dari orang kebanyakan, ternyata,\nmenjadikan suatu kelebihan yang bisa mengantarkan aku menjadi dokter forensik.\nHal yang mengejutkan lainnya, satu persatu pengalaman melihat yang tak kasat mata di ruang\nautopsi ketika menjalani tugas.\nPengalaman horror yang membuatku merinding semakin intens. Awalnya, aku bingung, tak\npercaya pada hal ghaib. Lambat laun, rasa takut dan tak percaya mulai menghilang.\nPesan-pesan dari pasien tak kasat mata semakin banyak dan membuatku kelabakan selama\nmenjadi dokter forensik. Kejadian-kejadian aneh semakin banyak di sekitarku. Apakah aku\nsanggup menjalani profesi sebagai dokter forensik ini? Misteri masa lalu pun terkuak ke\npermukaan, apa yang harus aku lakukan untuk menghadapi itu semua?",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665729616_gooddreamer_Black_Queen---PPTKM.jpeg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 14:23:01",
      created_at: "2022-10-14T06:40:16.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: null,
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: false,
      listed: true,
      total_purchased: 1,
    },
  },
  {
    id: 88,
    created_at: "2022-10-22T18:51:43.000000Z",
    updated_at: "2022-10-22T18:51:43.000000Z",
    novel: {
      id: 66,
      novel_price: 29,
      novel_uri: "janji-mecca-KHy",
      novel_title: "Janji Mecca",
      novel_sinopsis:
        "Tentang sebuah janji seorang perempuan bernama Mecca pada sahabatnya dan pada seseorang di masa lalunya. Mecca, berjanji pada Faris akan menunggunya hingga ia berhasil mencapai kesuksesan dan menjawab ucapan cintanya. Mecca pun berjanji pada Khaira akan membuatnya bahagia, apapun yang Khaira mau akan diberikannya.\n\n \n\nLalu bagaimana jika ternyata Khaira menginginkan Faris? Dalam diam Mecca merasa terhimpit di dalam dua janji yang dia buat sendiri. Apakah yang membuat Mecca akhirnya lebih mementingkan janjinya pada Khaira? Lalu bagaimana keadaan Faris?\n\n \n\nSimak cerita selengkapnya di Janji Mecca, bukan hanya persoalan cinta segitiga, persahabatan tapi tentang keluarga dan juga kehidupan lainnya.",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665730776_gooddreamer_Nisa-Noor--JM.jpeg",
      novel_rating: 4,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 14:28:23",
      created_at: "2022-10-14T06:59:36.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: null,
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: false,
      listed: true,
      total_purchased: 3,
    },
  },
  {
    id: 89,
    created_at: "2022-10-22T18:51:52.000000Z",
    updated_at: "2022-10-22T18:51:52.000000Z",
    novel: {
      id: 67,
      novel_price: 29,
      novel_uri: "love-scenario-dSC",
      novel_title: "Love Scenario",
      novel_sinopsis:
        "Kisah kehidupan antara sepasang kekasih yang terjalin dari bangku SMA,  di mana Ayra gadis cantik dan periang harus melanjutkan kuliahnya di Jakarta sedangkan Alfero kekasihnya kuliah di Singapore sesuai permintaan kedua orang tuanya. Mereka harus terpisah jarak, dan menjalani sebuah hubungan yang disebut dengan Long Distance Relationship (LDR).\n\nSetelah Alfero menyelesaikan pendidikan sarjananya, Alfero pun kembali ke Indonesia dan mereka\nkembali bersama, hanya saja disaat Perusahaan Papa Alfero mendapatkan masalah besar,  Alfero pun pergi ke Italy meninggalkan Ayra kembali pergi tanpa pamit dengan Ayra, dan membuat hubungan mereka pun semakin merenggang. \n\nBagaimanakah skenario cinta mereka berjalan? Apakah Ayra masih sanggup menunggu sang kekasih, yang meninggalkannya tanpa pesan?",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665731146_gooddreamer_Uthieecan---LS.jpeg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 14:23:30",
      created_at: "2022-10-14T07:05:46.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: "2022-12-03 00:00:00",
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: true,
      listed: true,
      total_purchased: 3,
    },
  },
  {
    id: 90,
    created_at: "2022-10-22T18:52:07.000000Z",
    updated_at: "2022-10-22T18:52:07.000000Z",
    novel: {
      id: 68,
      novel_price: 29,
      novel_uri: "the-everlasting-lullaby-FyS",
      novel_title: "The Everlasting Lullaby",
      novel_sinopsis:
        "Niat hati ingin mengakhiri rantai ironi dalam hidupnya, Iva justru kembali dihadapkan pada takdir yang semakin rumit setelah tiba-tiba terbangun dalam tubuh Titania. Meski begitu ia tidak menyerah begitu saja, Iva masih mencoba meninggalkan dunia-membunuh dirinya sendiri, sampai suatu hari sosok yang diagungkan para elf muncul.\n\nDewa Freyr menampakkan diri di hadapan Iva untuk menjelaskan alasan gadis itu terbangun di tubuh Titania. Siapa sangka sebuah Iva mengemban tugas yang berat dan mempertaruhkan keselamatan dua dunia, sehingga sang dewa menawarkan perjanjian kepada Iva. \n\nLantas, Apakah ia akan tetap berusaha mengakhiri hidupnya atau menerima tawaran untuk menjalankan tugas dari sang dewa? Perjanjian apa yang ditawarkan Freyr kepada Iva?",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665732457_gooddreamer_Audreana-Ivy---TEL.jpg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 14:54:25",
      created_at: "2022-10-14T07:27:38.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: null,
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: false,
      listed: true,
      total_purchased: 3,
    },
  },
  {
    id: 91,
    created_at: "2022-10-22T18:52:26.000000Z",
    updated_at: "2022-10-22T18:52:26.000000Z",
    novel: {
      id: 74,
      novel_price: 29,
      novel_uri: "cinta-sejagad-raya-hbJ",
      novel_title: "CINTA (SE)JAGAD RAYA",
      novel_sinopsis:
        "Apa yang akan kamu lakukan jika terjebak dalam kehidupan pernikahan dengan pasangan yang\npenuh gengsi?\n\nItulah kira-kira yang dialami oleh Raya. Harusnya dia beruntung diperistri oleh pemuda pujaan\nhatinya yang tak hanya rupawan, tapi juga berasal dari keluarga kaya. Namun apa jadinya jika\nternyata Jagad menikahinya hanya demi mencapai tujuannya sendiri?\nRaya bukanlah merupakan wanita tipe yang disukai Jagad. Tapi Jagad memutuskan untuk\nmenikahinya demi mendapat harta dan kepercayaan dari orangtuanya. Akibatnya, Raya yang harus\nmenjalani biduk pernikahan penuh sandiwara. Tak hanya harus berpura-pura bahagia di depan\norang-orang dekat mereka, Raya pun harus terima saat suami yang sangat dicintainya itu ternyata\nmalu untuk mengakuinya sebagai pasangan di depan teman-temannya.",
      novel_cover:
        "https://latte-api.gooddreamer.id/storage/novels/1665736915_gooddreamer_Reinee-Raharjo---CJR.jpeg",
      novel_rating: 0,
      active: 1,
      status: 2,
      extend_status: 0,
      bundle: 0,
      free_chapter: 5,
      published_at: "2022-10-14 16:16:06",
      created_at: "2022-10-14T08:41:56.000000Z",
      updated_at: "2022-11-19T11:52:10.000000Z",
      expired_at: null,
      chapters_count: null,
      readers_count: null,
      word_count: 0,
      purchased: false,
      listed: true,
      total_purchased: 2,
    },
  },
];
