const images = {
  addCard: require("../assets/images/add-card.png"),
  badge: require("../assets/images/badge.png"),
  boxClose: require("../assets/images/box-close.png"),
  boxOpen: require("../assets/images/box-open.png"),
  brokenCard: require("../assets/images/broken-card.png"),
  cardDouble: require("../assets/images/card-double.png"),
  cart: require("../assets/images/cart.png"),
  check: require("../assets/images/check.png"),
  cloud: require("../assets/images/cloud.png"),
  comments: require("../assets/images/comments.png"),
  connectivity7: require("../assets/images/connectivity-7.png"),
  connectivity8: require("../assets/images/connectivity-8.png"),
  connectivity9: require("../assets/images/connectivity-9.png"),
  connectivity10: require("../assets/images/connectivity-10.png"),
  connectivity: require("../assets/images/connectivity.png"),
  coupon: require("../assets/images/coupon.png"),
  decline: require("../assets/images/decline.png"),
  diamond: require("../assets/images/diamond.png"),
  email: require("../assets/images/email.png"),
  ghost: require("../assets/images/ghost.png"),
  gift: require("../assets/images/gift.png"),
  handGesture: require("../assets/images/hand-gesture.png"),
  handshake: require("../assets/images/handshake.png"),
  happy: require("../assets/images/happy.png"),
  hourglass: require("../assets/images/hourglass.png"),
  mailBox: require("../assets/images/mail-box.png"),
  mailEmpty: require("../assets/images/mail-empty.png"),
  mailSad: require("../assets/images/mail-sad.png"),
  messages: require("../assets/images/messages.png"),
  money: require("../assets/images/money.png"),
  openBook: require("../assets/images/open-book.png"),
  openBook1: require("../assets/images/open-book1.png"),
  password: require("../assets/images/password.png"),
  podium: require("../assets/images/podium.png"),
  search: require("../assets/images/search.png"),
  shoppingCart: require("../assets/images/shopping-cart.png"),
  star: require("../assets/images/star.png"),
  userExperience: require("../assets/images/user-experience.png"),
  user: require("../assets/images/user.png"),
  wallet6: require("../assets/images/wallet-6.png"),
  walletEmpty: require("../assets/images/wallet-empty.png"),
  winner: require("../assets/images/winner.png"),
  witch: require("../assets/images/witch.png"),
};

export default images;
